-- 12 diff-VERIFIED VIEW(s) — SQL Server -> MariaDB/MySQL. Generated by `migrator`.
-- Only objects whose result matched the SQL Server original exactly are included.
USE EXCHANGESYS2026;
SET NAMES utf8mb4;
SET collation_connection='utf8mb4_unicode_ci';
SET SESSION sql_mode='IGNORE_SPACE,NO_ENGINE_SUBSTITUTION';   -- allows 'func (x)' spacing in legacy T-SQL

CREATE OR REPLACE VIEW `COMMTION_RETVIEW` AS select abs ( a.Debit - A.Credit) as commion , A.InsertDate ,A.AccIDFrom , a.AccBranchID  ,B.BName ,
CASE  WHEN  a.Debit >A.Credit THEN 'Debit' ELSE 'Credit' END STATUESSTRING 
from `ExSyAccounts_AccSafeActivityTb` AS A 
LEFT JOIN CoBranch AS B ON A.AccBranchID = B.ID
  where  OperationTypeID = 94;

CREATE OR REPLACE VIEW `ExchangeAccData_DRiverFrom` AS SELECT 
            x.AccCode,
            x.AccID,
            x.AccName,
            x.TransDate,
            x.TransValue,
            x.Type_trns,
            x.commint,
            x.Code,
            x.STates_spinng,
            x.Type_from
			,c.id
			,x.IsActive , 
			case when  x.STates_spinng = 'غير معتمده'  then  1  
			when  x.STates_spinng = 'غير مسلمه'  then  2
			when  x.STates_spinng = 'مسلمه'  then  3
			when  x.STates_spinng = 'تم الايداع في الحساب'  then  3
			else 
			3
			end  as STates_Ineger
			,ServiceName 
			,CName , 
			TransPrice , 
			NetTotal , 
			ServiceExVal  ,
			Notes
			,Driver_ID
        FROM (
            
            SELECT 
                a.TransDate,
                a.TransValue,
                c.AccName,
                CAST(c.AccCode AS CHAR) AS AccCode,
                b.AccID,
                a.IsActive,
                a.Code,
                'تحويل بين الحسبات' AS Type_trns,
                0 AS commint,
                'تم الايداع في الحساب' AS STates_spinng,
                1 AS Type_from 

				,  ''  as ServiceName  
				 ,  '' as CName 
				 ,0.00 as TransPrice , 
				 0.00 as NetTotal , 
				 0.00  as ServiceExVal  ,
				 a.Notes as Notes  ,
				  a.Driver_ID
            FROM TransBetweenAccountsTB a
            INNER JOIN AccountsTb b ON a.TransFrom = b.AccID
            INNER JOIN AccountsTb c ON a.TransTo = c.AccID

            UNION ALL

            
            SELECT 
                a.InsertDate,
                a.OverallVal,
                a.SenderName,
                CAST(a.Code AS CHAR),
               IFNULL( a.AccFrom,0)   ,
                a.IsActive,
                a.Code,
                'حوالة داخلية' AS Type_trns,
                  a.ExVal,
                d.SName  as     STates_spinng,
                2 AS Type_from
					,  ''  as ServiceName  
				 ,  '' as CName 
				 ,0.00 as TransPrice , 
				 0.00 as NetTotal , 
				 0.00 as ServiceExVal  ,
				 a.Notes as Notes 
				 ,a.Driver_ID
            FROM InternalEx a
            
			inner join InternalEx_Stautes as d on a.ConfirmType = d.ConfirmType

            UNION ALL

     
           
            SELECT 
			
                a.InsertDate,
                a.CurrRecievedVal,
                a.RecievedName,
                CAST(a.RPhone1 AS CHAR),
                IFNULL( a.AccFrom,0) ,
                a.IsActive,
                a.Code,
                'حوالة خارجية',
                a.ExVal,
                CASE
                    WHEN a.IsCanceled = 1 THEN 'قيد الإلغاء'
                    WHEN a.IsCanceled IN (2, 7) THEN 'ملغية'
                    WHEN a.IsCanceled = 0 AND a.IsConfirmed = 0 THEN 'غير معتمده'
                    WHEN a.IsCanceled = 0 AND a.IsConfirmed = 1 THEN 'معتمده'
                END AS STates_spinng,
                3 AS Type_from
				,c.ServiceName
				 , d.CName
				 ,a.TransPrice 
				 ,a.NetTotal 
				 ,a.ServiceExVal
				,a.Notes
				 ,a.Driver_ID
            FROM ExternalEx a
           
			inner join ExtTraServiceTypeTb as c on a.ServiceType = c.ID
			inner join CountiresTb as d on a.CountryIDTo = d.ID
        ) AS x
		join DriversTb as b on x.Driver_ID=b.ID
        INNER JOIN users c ON b.accontID = c.AccID;

CREATE OR REPLACE VIEW `getInfo` AS SELECT 
        b.AccID, 
        b.AccName, 
        b.BranchID, 
        a.Countries,  
        b.AccCode, 
        a.phone, 
        a.id,  
        c.BName, 
        d.CName, 
        d.DefualtCurrency, 
        d.ID as Countires_ID,  
        e.CuName,  
        e.CurCode, 
        a.UeserType
		,a.National_number
		, a.created_at
    FROM users AS a  
    INNER JOIN AccountsTb AS b ON a.AccID = b.AccID  
    INNER JOIN CoBranch AS c ON b.BranchID = c.ID 
    INNER JOIN CountiresTb AS d ON c.CountryID = d.ID 
    INNER JOIN CurrencyMainTb AS e ON d.DefualtCurrency = e.ID 
union 
select IFNULL(a.AccID ,0),a.phone ,a.BrancchID , a.Countries , 0 , a.phone , a.id , b.BName ,  d.CName, 
        d.DefualtCurrency, 
        d.ID as Countires_ID,  
		
	
        e.CuName,  
        e.CurCode, 
        a.UeserType
		,a.National_number
		, a.created_at
		from users as a
inner join CoBranch as b on a.BrancchID= b.ID
  INNER JOIN CountiresTb AS d ON b.CountryID = d.ID 
     INNER JOIN CurrencyMainTb AS e ON d.DefualtCurrency = e.ID 
	 where a.UeserType = 6;

CREATE OR REPLACE VIEW `InternalEx_SelectType_View_not_coustmers` AS SELECT
              x.Code          
             , x.InsertDate   
              ,x.SenderName   
            ,  x.RecievedName 
			 , x.RPhone       
             , x.OverallVal   
              ,x.ExVal        
             , x.BName        
             , x.CaseStauts   
             , x.SendStatus   
              , x.BranchRecievedID
			  , x.BranchDeliveredID
      FROM
              (   SELECT
                          a.Code,
                          a.InsertDate,
                          a.SenderName,
                          a.RecievedName,
						  a.RPhone1 as RPhone,
                          a.OverallVal,
                          a.ExVal,
                          b.BName,
                          CASE
                                              WHEN a.BranchDeliveredID > 0
                                                THEN
                                                c.BName
                                              ELSE
                                              'خارج المنظومة'
                                      END AS CaseStauts,
                          CASE
                                              WHEN a.ConfirmType = 1
                                                THEN
                                                'جاهزة للتسليم'
                                      END AS SendStatus,
                          a.BranchRecievedID 
						  ,a.BranchDeliveredID
                  FROM
                          InternalEx AS a
                      LEFT JOIN
                        CoBranch AS b
                            ON a.BranchRecievedID = b.ID
                      LEFT JOIN
                        CoBranch AS c
                            ON a.BranchDeliveredID = c.ID
                  WHERE
                        a.ConfirmType= 1
                        ) AS x;

CREATE OR REPLACE VIEW `NewCurrencyPriceOwnDetailsTb_wep` AS select  a.ID,a.SalePrice , a.BuyPrice , b.InsertDate , b.InsertTime  , c.CName,cmt.CuName  from 
              NewCurrencyPriceOwnDetailsTb AS a
              LEFT JOIN NewCurrencyPricesOwnTb AS b ON a.CPID=b.ID
			  LEFT join CountiresTb as c on b.CountryID =c.ID and a.CurrencyIDTo = c.DefualtCurrency
        LEFT JOIN CurrencyMainTb cmt ON a.CurrencyIDTo=cmt.ID
			  WHERE
              a.CurrencyIDFrom = 1
              AND b.PriceType=2           
			  and b.AccountType =  3;

CREATE OR REPLACE VIEW `TransCancelRequestTb_LoadToIssued` AS SELECT
          a.ID,
          a.InsertDate,
          a.ReasonID,
          a.SafeID,
          a.BranchID,
          a.ISID,
          a.ISIDTYPE,
          a.Notes,
          a.IsActive,
          a.IsConfirmCancel,
          a.IsCanceledRequest,
          a.RefusuedRequset
  FROM
          TransCancelRequestTb AS a;

CREATE OR REPLACE VIEW `UeserType_mobile_fill_Daily_transfer_preparer_locukupEdit` AS select a.id,a.Name_type  from UeserType_mobile as a 
EXCEPT
select a.ueserTyp,b.Name_type from Daily_transfer_preparer_schedule as a 
inner join UeserType_mobile as b on a.ueserTyp = b.id;

CREATE OR REPLACE VIEW `View_CBranch` AS SELECT ID AS FBranchID,CASE WHEN IsMain=1 then 50.000 WHEN BranchType=1 AND IsMain=0 THEN 33.000 WHEN BranchType=3 THEN 50.00 END AS FBRate,ID AS SBranchID,CASE WHEN IsMain=1 then 50.000 WHEN BranchType=1 AND IsMain=0 THEN 33.000 WHEN BranchType=3 THEN 0 END AS SBRate FROM CoBranch;

CREATE OR REPLACE VIEW `View_SHOWBRANCHSCREENS_ROLE` AS SELECT A.ScreenID, A.CanShow, A.CanOpen, A.CanAdd, A.CanEdit, A.CanDelete, A.CanPrint, E.CanShow AS IsShow, E.RPID, A.ID, A.ProfileID, C.ID AS Expr1, B.USID, B.UName, B.USettingProfileID, 
                         D.ID AS Expr2
FROM            UserAccessProfileDetails AS A LEFT OUTER JOIN
                         TB_Users AS B ON A.ProfileID = B.USettingProfileID LEFT OUTER JOIN
                         UserAccessProfileName AS C ON A.ProfileID = C.ID LEFT OUTER JOIN
                         MainTabTb AS D ON A.ScreenID = D.ID LEFT OUTER JOIN
                         RibbonPermission AS E ON C.ID = E.ProfileID;

CREATE OR REPLACE VIEW `VW_AccountBalances` AS SELECT
    AccIDFrom AS AccID,
    CurrencyID,
    SUM(IFNULL(Credit,0) - IFNULL(Debit,0)) AS Balance
FROM ExSyAccountsCurrency_AccSafeActivityTb
WHERE IsActive = 1
GROUP BY
    AccIDFrom,
    CurrencyID;

CREATE OR REPLACE VIEW `vw_SalaryCalc` AS SELECT        ROW_NUMBER() OVER (ORDER BY ID ASC) AS '#', ID,BranchID, EMPNAME AS 'اسم الموظف', SalaryVal AS 'قيمة الراتب', BonusVal AS 'إجمالي العلاوات', 
SalaryVal + BonusVal AS 'الإجمالي الكلي'
FROM            EmployeeTb;

CREATE OR REPLACE VIEW `VW_SALARYCALCLAST` AS SELECT
          A.ID,
          A.AccID,
          A.EMPNAME                               AS `اسم الموظف`,
          D.BName                                 AS الفرع,
          IFNULL(A.SalaryVal, 0.000)              AS `الراتب الأساسي`,
          EMP_GetConstanceIncreaseToals(A.ID) AS `علاوات ثابتة`,
          EMP_GetTempIncreaseToals(A.ID)      AS `علاوات أخرى`,
          EMP_GetDiscTtoals(A.ID)             AS `خصميات متنوعة`,
          EMP_GetLeaveDiscountTotal(A.ID)     AS `خصم إجازة`,
          EMP_GetADVPMNTTtoals(A.ID)          AS `خصم السلفة`,
          EMP_GetADVPMNTTtoalsIndivdual(A.ID) AS `باقي السلفة`,
          EMP_GetNettoals(A.ID)               AS الصافي,
          A.BranchID,         
          A.PHONE1                                AS `رقم هاتف الموظف`,
          A.CODE                                  AS `الرقمي الوظيفي`,
          A.EMPDATE,
          a.BankSalaryCalc,
          A.ISACTIVE,
          a.ID AS EMPID,
          c.ECNAME  AS التصنيف
  FROM
          EmployeeTb AS A
      LEFT OUTER JOIN
        CoBranch AS D
          ON A.BranchID = D.ID
         LEFT JOIN
         EmployeeClassificationTb  c
         ON a.CLASSIFICATION=c.ID

  WHERE
          (A.ISACTIVE = 1);

