'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection

Namespace ExchangeSystem.DAL
	<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="EXCHANGESYS")>
	Partial Public Class DataClasses1DataContext
		Inherits System.Data.Linq.DataContext

		Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()

#Region "Extensibility Method Definitions"
		Partial Private Sub OnCreated()
		End Sub
		Partial Private Sub InsertTB_User(instance As TB_User)
		End Sub
		Partial Private Sub UpdateTB_User(instance As TB_User)
		End Sub
		Partial Private Sub DeleteTB_User(instance As TB_User)
		End Sub
		Partial Private Sub InsertUserAccessProfileDetail(instance As UserAccessProfileDetail)
		End Sub
		Partial Private Sub UpdateUserAccessProfileDetail(instance As UserAccessProfileDetail)
		End Sub
		Partial Private Sub DeleteUserAccessProfileDetail(instance As UserAccessProfileDetail)
		End Sub
		Partial Private Sub InsertUserAccessProfileName(instance As UserAccessProfileName)
		End Sub
		Partial Private Sub UpdateUserAccessProfileName(instance As UserAccessProfileName)
		End Sub
		Partial Private Sub DeleteUserAccessProfileName(instance As UserAccessProfileName)
		End Sub
#End Region

		Public Sub New()
			MyBase.New(Global.ExchangeSystem.My.MySettings.Default.EXCHANGESYSConnectionString, mappingSource)
			OnCreated()
		End Sub

		Public Sub New(ByVal connection As String)
			MyBase.New(connection, mappingSource)
			OnCreated()
		End Sub

		Public Sub New(ByVal connection As System.Data.IDbConnection)
			MyBase.New(connection, mappingSource)
			OnCreated()
		End Sub

		Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated()
		End Sub

		Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated()
		End Sub

		Public ReadOnly Property TB_Users() As System.Data.Linq.Table(Of TB_User)
			Get
				Return Me.GetTable(Of TB_User)
			End Get
		End Property

		Public ReadOnly Property UserAccessProfileDetails() As System.Data.Linq.Table(Of UserAccessProfileDetail)
			Get
				Return Me.GetTable(Of UserAccessProfileDetail)
			End Get
		End Property

		Public ReadOnly Property UserAccessProfileNames() As System.Data.Linq.Table(Of UserAccessProfileName)
			Get
				Return Me.GetTable(Of UserAccessProfileName)
			End Get
		End Property
	End Class

	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TB_Users")>
	Partial Public Class TB_User
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged

		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)

		Private _USID As Integer

		Private _UName As String

		Private _UNameLog As String

		Private _UPass As String

		Private _IsActive As System.Nullable(Of Boolean)

		Private _BranchID As System.Nullable(Of Integer)

		Private _ProfileID As System.Nullable(Of Integer)

		Private _TypeID As System.Nullable(Of Byte)

		Private _AccID As System.Nullable(Of Long)

		Private _USettingProfileID As System.Nullable(Of Integer)

#Region "Extensibility Method Definitions"
		Partial Private Sub OnLoaded()
		End Sub
		Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
		End Sub
		Partial Private Sub OnCreated()
		End Sub
		Partial Private Sub OnUSIDChanging(value As Integer)
		End Sub
		Partial Private Sub OnUSIDChanged()
		End Sub
		Partial Private Sub OnUNameChanging(value As String)
		End Sub
		Partial Private Sub OnUNameChanged()
		End Sub
		Partial Private Sub OnUNameLogChanging(value As String)
		End Sub
		Partial Private Sub OnUNameLogChanged()
		End Sub
		Partial Private Sub OnUPassChanging(value As String)
		End Sub
		Partial Private Sub OnUPassChanged()
		End Sub
		Partial Private Sub OnIsActiveChanging(value As System.Nullable(Of Boolean))
		End Sub
		Partial Private Sub OnIsActiveChanged()
		End Sub
		Partial Private Sub OnBranchIDChanging(value As System.Nullable(Of Integer))
		End Sub
		Partial Private Sub OnBranchIDChanged()
		End Sub
		Partial Private Sub OnProfileIDChanging(value As System.Nullable(Of Integer))
		End Sub
		Partial Private Sub OnProfileIDChanged()
		End Sub
		Partial Private Sub OnTypeIDChanging(value As System.Nullable(Of Byte))
		End Sub
		Partial Private Sub OnTypeIDChanged()
		End Sub
		Partial Private Sub OnAccIDChanging(value As System.Nullable(Of Long))
		End Sub
		Partial Private Sub OnAccIDChanged()
		End Sub
		Partial Private Sub OnUSettingProfileIDChanging(value As System.Nullable(Of Integer))
		End Sub
		Partial Private Sub OnUSettingProfileIDChanged()
		End Sub
#End Region

		Public Sub New()
			MyBase.New
			OnCreated()
		End Sub

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=True, IsDbGenerated:=True)>
		Public Property USID() As Integer
			Get
				Return Me._USID
			End Get
			Set
				If ((Me._USID = Value) _
							= False) Then
					Me.OnUSIDChanging(Value)
					Me.SendPropertyChanging()
					Me._USID = Value
					Me.SendPropertyChanged("USID")
					Me.OnUSIDChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UName", DbType:="NVarChar(MAX)")>
		Public Property UName() As String
			Get
				Return Me._UName
			End Get
			Set
				If (String.Equals(Me._UName, Value) = False) Then
					Me.OnUNameChanging(Value)
					Me.SendPropertyChanging()
					Me._UName = Value
					Me.SendPropertyChanged("UName")
					Me.OnUNameChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UNameLog", DbType:="NVarChar(MAX)")>
		Public Property UNameLog() As String
			Get
				Return Me._UNameLog
			End Get
			Set
				If (String.Equals(Me._UNameLog, Value) = False) Then
					Me.OnUNameLogChanging(Value)
					Me.SendPropertyChanging()
					Me._UNameLog = Value
					Me.SendPropertyChanged("UNameLog")
					Me.OnUNameLogChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UPass", DbType:="NVarChar(MAX)")>
		Public Property UPass() As String
			Get
				Return Me._UPass
			End Get
			Set
				If (String.Equals(Me._UPass, Value) = False) Then
					Me.OnUPassChanging(Value)
					Me.SendPropertyChanging()
					Me._UPass = Value
					Me.SendPropertyChanged("UPass")
					Me.OnUPassChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsActive", DbType:="Bit")>
		Public Property IsActive() As System.Nullable(Of Boolean)
			Get
				Return Me._IsActive
			End Get
			Set
				If (Me._IsActive.Equals(Value) = False) Then
					Me.OnIsActiveChanging(Value)
					Me.SendPropertyChanging()
					Me._IsActive = Value
					Me.SendPropertyChanged("IsActive")
					Me.OnIsActiveChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BranchID", DbType:="Int")>
		Public Property BranchID() As System.Nullable(Of Integer)
			Get
				Return Me._BranchID
			End Get
			Set
				If (Me._BranchID.Equals(Value) = False) Then
					Me.OnBranchIDChanging(Value)
					Me.SendPropertyChanging()
					Me._BranchID = Value
					Me.SendPropertyChanged("BranchID")
					Me.OnBranchIDChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProfileID", DbType:="Int")>
		Public Property ProfileID() As System.Nullable(Of Integer)
			Get
				Return Me._ProfileID
			End Get
			Set
				If (Me._ProfileID.Equals(Value) = False) Then
					Me.OnProfileIDChanging(Value)
					Me.SendPropertyChanging()
					Me._ProfileID = Value
					Me.SendPropertyChanged("ProfileID")
					Me.OnProfileIDChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TypeID", DbType:="TinyInt")>
		Public Property TypeID() As System.Nullable(Of Byte)
			Get
				Return Me._TypeID
			End Get
			Set
				If (Me._TypeID.Equals(Value) = False) Then
					Me.OnTypeIDChanging(Value)
					Me.SendPropertyChanging()
					Me._TypeID = Value
					Me.SendPropertyChanged("TypeID")
					Me.OnTypeIDChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccID", DbType:="BigInt")>
		Public Property AccID() As System.Nullable(Of Long)
			Get
				Return Me._AccID
			End Get
			Set
				If (Me._AccID.Equals(Value) = False) Then
					Me.OnAccIDChanging(Value)
					Me.SendPropertyChanging()
					Me._AccID = Value
					Me.SendPropertyChanged("AccID")
					Me.OnAccIDChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USettingProfileID", DbType:="Int")>
		Public Property USettingProfileID() As System.Nullable(Of Integer)
			Get
				Return Me._USettingProfileID
			End Get
			Set
				If (Me._USettingProfileID.Equals(Value) = False) Then
					Me.OnUSettingProfileIDChanging(Value)
					Me.SendPropertyChanging()
					Me._USettingProfileID = Value
					Me.SendPropertyChanged("USettingProfileID")
					Me.OnUSettingProfileIDChanged()
				End If
			End Set
		End Property

		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging

		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing) _
						= False) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub

		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing) _
						= False) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class

	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.UserAccessProfileDetails")>
	Partial Public Class UserAccessProfileDetail
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged

		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)

		Private _ID As Integer

		Private _ProfileID As Integer

		Private _ScreenID As Integer

		Private _CanShow As Boolean

		Private _CanOpen As Boolean

		Private _CanAdd As Boolean

		Private _CanEdit As Boolean

		Private _CanDelete As Boolean

		Private _CanPrint As Boolean

#Region "Extensibility Method Definitions"
		Partial Private Sub OnLoaded()
		End Sub
		Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
		End Sub
		Partial Private Sub OnCreated()
		End Sub
		Partial Private Sub OnIDChanging(value As Integer)
		End Sub
		Partial Private Sub OnIDChanged()
		End Sub
		Partial Private Sub OnProfileIDChanging(value As Integer)
		End Sub
		Partial Private Sub OnProfileIDChanged()
		End Sub
		Partial Private Sub OnScreenIDChanging(value As Integer)
		End Sub
		Partial Private Sub OnScreenIDChanged()
		End Sub
		Partial Private Sub OnCanShowChanging(value As Boolean)
		End Sub
		Partial Private Sub OnCanShowChanged()
		End Sub
		Partial Private Sub OnCanOpenChanging(value As Boolean)
		End Sub
		Partial Private Sub OnCanOpenChanged()
		End Sub
		Partial Private Sub OnCanAddChanging(value As Boolean)
		End Sub
		Partial Private Sub OnCanAddChanged()
		End Sub
		Partial Private Sub OnCanEditChanging(value As Boolean)
		End Sub
		Partial Private Sub OnCanEditChanged()
		End Sub
		Partial Private Sub OnCanDeleteChanging(value As Boolean)
		End Sub
		Partial Private Sub OnCanDeleteChanged()
		End Sub
		Partial Private Sub OnCanPrintChanging(value As Boolean)
		End Sub
		Partial Private Sub OnCanPrintChanged()
		End Sub
#End Region

		Public Sub New()
			MyBase.New
			OnCreated()
		End Sub

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=True, IsDbGenerated:=True)>
		Public Property ID() As Integer
			Get
				Return Me._ID
			End Get
			Set
				If ((Me._ID = Value) _
							= False) Then
					Me.OnIDChanging(Value)
					Me.SendPropertyChanging()
					Me._ID = Value
					Me.SendPropertyChanged("ID")
					Me.OnIDChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProfileID", DbType:="Int NOT NULL")>
		Public Property ProfileID() As Integer
			Get
				Return Me._ProfileID
			End Get
			Set
				If ((Me._ProfileID = Value) _
							= False) Then
					Me.OnProfileIDChanging(Value)
					Me.SendPropertyChanging()
					Me._ProfileID = Value
					Me.SendPropertyChanged("ProfileID")
					Me.OnProfileIDChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ScreenID", DbType:="Int NOT NULL")>
		Public Property ScreenID() As Integer
			Get
				Return Me._ScreenID
			End Get
			Set
				If ((Me._ScreenID = Value) _
							= False) Then
					Me.OnScreenIDChanging(Value)
					Me.SendPropertyChanging()
					Me._ScreenID = Value
					Me.SendPropertyChanged("ScreenID")
					Me.OnScreenIDChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CanShow", DbType:="Bit NOT NULL")>
		Public Property CanShow() As Boolean
			Get
				Return Me._CanShow
			End Get
			Set
				If ((Me._CanShow = Value) _
							= False) Then
					Me.OnCanShowChanging(Value)
					Me.SendPropertyChanging()
					Me._CanShow = Value
					Me.SendPropertyChanged("CanShow")
					Me.OnCanShowChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CanOpen", DbType:="Bit NOT NULL")>
		Public Property CanOpen() As Boolean
			Get
				Return Me._CanOpen
			End Get
			Set
				If ((Me._CanOpen = Value) _
							= False) Then
					Me.OnCanOpenChanging(Value)
					Me.SendPropertyChanging()
					Me._CanOpen = Value
					Me.SendPropertyChanged("CanOpen")
					Me.OnCanOpenChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CanAdd", DbType:="Bit NOT NULL")>
		Public Property CanAdd() As Boolean
			Get
				Return Me._CanAdd
			End Get
			Set
				If ((Me._CanAdd = Value) _
							= False) Then
					Me.OnCanAddChanging(Value)
					Me.SendPropertyChanging()
					Me._CanAdd = Value
					Me.SendPropertyChanged("CanAdd")
					Me.OnCanAddChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CanEdit", DbType:="Bit NOT NULL")>
		Public Property CanEdit() As Boolean
			Get
				Return Me._CanEdit
			End Get
			Set
				If ((Me._CanEdit = Value) _
							= False) Then
					Me.OnCanEditChanging(Value)
					Me.SendPropertyChanging()
					Me._CanEdit = Value
					Me.SendPropertyChanged("CanEdit")
					Me.OnCanEditChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CanDelete", DbType:="Bit NOT NULL")>
		Public Property CanDelete() As Boolean
			Get
				Return Me._CanDelete
			End Get
			Set
				If ((Me._CanDelete = Value) _
							= False) Then
					Me.OnCanDeleteChanging(Value)
					Me.SendPropertyChanging()
					Me._CanDelete = Value
					Me.SendPropertyChanged("CanDelete")
					Me.OnCanDeleteChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CanPrint", DbType:="Bit NOT NULL")>
		Public Property CanPrint() As Boolean
			Get
				Return Me._CanPrint
			End Get
			Set
				If ((Me._CanPrint = Value) _
							= False) Then
					Me.OnCanPrintChanging(Value)
					Me.SendPropertyChanging()
					Me._CanPrint = Value
					Me.SendPropertyChanged("CanPrint")
					Me.OnCanPrintChanged()
				End If
			End Set
		End Property

		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging

		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing) _
						= False) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub

		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing) _
						= False) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class

	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.UserAccessProfileName")>
	Partial Public Class UserAccessProfileName
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged

		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)

		Private _ID As Integer

		Private _Name As String

#Region "Extensibility Method Definitions"
		Partial Private Sub OnLoaded()
		End Sub
		Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
		End Sub
		Partial Private Sub OnCreated()
		End Sub
		Partial Private Sub OnIDChanging(value As Integer)
		End Sub
		Partial Private Sub OnIDChanged()
		End Sub
		Partial Private Sub OnNameChanging(value As String)
		End Sub
		Partial Private Sub OnNameChanged()
		End Sub
#End Region

		Public Sub New()
			MyBase.New
			OnCreated()
		End Sub

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=True, IsDbGenerated:=True)>
		Public Property ID() As Integer
			Get
				Return Me._ID
			End Get
			Set
				If ((Me._ID = Value) _
							= False) Then
					Me.OnIDChanging(Value)
					Me.SendPropertyChanging()
					Me._ID = Value
					Me.SendPropertyChanged("ID")
					Me.OnIDChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="NVarChar(MAX)")>
		Public Property Name() As String
			Get
				Return Me._Name
			End Get
			Set
				If (String.Equals(Me._Name, Value) = False) Then
					Me.OnNameChanging(Value)
					Me.SendPropertyChanging()
					Me._Name = Value
					Me.SendPropertyChanged("Name")
					Me.OnNameChanged()
				End If
			End Set
		End Property

		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging

		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing) _
						= False) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub

		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing) _
						= False) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
End Namespace
